### ISSUE TITLE
Requests don't seem to have a timeout, this can lead to indefinite hanging

### ISSUE THREAD

**Issue by dabacon** [PennyLaneAI/PennyLane-IonQ#26]
We have observed calls that seem to hang forever.  Looking over the client it doesn't look like it has a default timeout set on requests, and it is possible that the get to retrieve jobs while polling for results hangs forever.

**Comment by co9olguy** [comment]
Hi @dabacon, with the new PR merged (thanks!), are you still observing the troublesome calls that you found before? Or shall we close this particular issue now?

**Comment by dabacon** [comment]
This appears to have been fixed.  We have seen some connection timeouts, but suspect these are local issues.

**Comment by co9olguy** [comment]
:100:
